name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            name: windows
            executable: dormitory-manager.exe
          - os: macos-latest
            name: macos
            executable: dormitory-manager.app

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build executable (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        pyinstaller --onefile --windowed --name="dormitory-manager" main.py

    - name: Build executable (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        pyinstaller --onedir --windowed --name="dormitory-manager" main.py

    - name: Create archive (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        Compress-Archive -Path "dist/dormitory-manager.exe" -DestinationPath "dormitory-manager-windows.zip"

    - name: Create archive (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        cd dist && zip -r ../dormitory-manager-macos.zip dormitory-manager.app

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.name }}
        path: dormitory-manager-${{ matrix.name }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - name: Download Windows artifact
      uses: actions/download-artifact@v4
      with:
        name: windows

    - name: Download macOS artifact
      uses: actions/download-artifact@v4
      with:
        name: macos

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dormitory-manager-windows.zip
          dormitory-manager-macos.zip
        tag_name: ${{ github.ref_name }}
        name: Dormitory Manager ${{ github.ref_name }}
        body: |
          ## Download
          - Windows: dormitory-manager-windows.zip
          - macOS: dormitory-manager-macos.zip
          
          ## Installation
          1. Download the file for your operating system
          2. Extract and run
          3. Default password: admin123
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}